version: '3'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wp_db
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf:cached
      - ./docker/db/sql:/docker-entrypoint-initdb.d/:cached
        
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./theme:/var/www/html/wp-content/themes/kiwi-dev-block-theme/
      - ./uploads:/var/www/html/wp-content/uploads/
      - ./plugins/wp-multibyte-patch:/var/www/html/wp-content/plugins/wp-multibyte-patch/

volumes:
  db-store:
  php-fpm-socket:
